# Generated by Django 2.1.7 on 2019-03-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_foodmania'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodmania',
            old_name='user_Name',
            new_name='Restaurant_Description',
        ),
        migrations.RenameField(
            model_name='foodmania',
            old_name='user_email',
            new_name='Restaurant_Name',
        ),
        migrations.AddField(
            model_name='foodmania',
            name='Restaurant_email',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
