# Generated by Django 2.1.7 on 2019-03-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190329_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmania',
            name='Restaurant_Description',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='foodmania',
            name='Restaurant_Name',
            field=models.CharField(default='Restaurant', max_length=200),
        ),
        migrations.AddField(
            model_name='foodmania',
            name='Restaurant_email',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
