# Generated by Django 2.1.7 on 2019-03-29 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190329_0945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='foodmania',
        ),
    ]
