# Generated by Django 2.1.7 on 2019-03-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0007_delete_foodmania'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_Name', models.CharField(default='Restaurant', max_length=200)),
                ('Restaurant_email', models.CharField(default='null', max_length=200)),
                ('Restaurant_Description', models.CharField(default='none', max_length=200)),
            ],
        ),
    ]
