# Generated by Django 2.1.7 on 2019-03-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='Restaurant_image',
            field=models.ImageField(default='no image', upload_to='static/main/images/'),
        ),
    ]
