# Generated by Django 2.1.7 on 2019-04-04 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190329_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_name', models.CharField(default='none', max_length=200)),
                ('Food_price', models.IntegerField()),
                ('Food_slug', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Menu_Title', models.CharField(default='not set', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name_plural': 'Restaurants'},
        ),
        migrations.AddField(
            model_name='menu',
            name='Menu_categlog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Restaurant', verbose_name='Restaurants'),
        ),
        migrations.AddField(
            model_name='food',
            name='Menu_items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Menu', verbose_name='Menus'),
        ),
    ]
