# Generated by Django 2.1.7 on 2019-04-05 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190404_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='Menu_categlog',
        ),
        migrations.RemoveField(
            model_name='food',
            name='Menu_items',
        ),
        migrations.AddField(
            model_name='food',
            name='Restaurant_items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Restaurant', verbose_name='Restaurants'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Restaurant_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
