# Generated by Django 2.1.7 on 2019-04-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190405_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='none', max_length=200)),
                ('Message', models.CharField(default='none', max_length=200)),
            ],
        ),
    ]
