# Generated by Django 2.1.7 on 2019-04-09 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orders_id', models.CharField(default='0', max_length=200)),
                ('Orders_total', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Order_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_name', models.CharField(default='none', max_length=200)),
                ('Food_quantity', models.IntegerField(default=0)),
                ('Food_from', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Order', verbose_name='Orders')),
            ],
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Message',
            field=models.TextField(default='none', max_length=200),
        ),
    ]
