# Generated by Django 2.1.7 on 2019-04-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190409_1448'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='order_content',
            order_with_respect_to='Food_from',
        ),
    ]
