# Generated by Django 2.1.7 on 2019-04-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190409_1541'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='order',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='order_content',
            order_with_respect_to=None,
        ),
    ]
