# Generated by Django 2.1.7 on 2019-04-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190409_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.CharField(default='not given', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_no',
            field=models.CharField(default='not given', max_length=200),
        ),
    ]
