# Generated by Django 2.1.7 on 2019-04-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190410_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='Restaurant_Name',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
