# Generated by Django 2.1.7 on 2019-04-11 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_food_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_content',
            name='Food_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Order', verbose_name='Orders'),
        ),
    ]
